<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" ignored="7" total="9" passed="0">
  <reporter-output>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[result/screenshot/2018_08_10_14_18_39_toLose.jpg]]>
    </line>
    <line>
      <![CDATA[<img src="../../result/screenshot/2018_08_10_14_18_39_toLose.jpg"/>]]>
    </line>
    <line>
      <![CDATA[result/screenshot/2018_08_10_14_18_54_toLose.jpg]]>
    </line>
    <line>
      <![CDATA[<img src="../../result/screenshot/2018_08_10_14_18_54_toLose.jpg"/>]]>
    </line>
    <line>
      <![CDATA[RunCount=2]]>
    </line>
    <line>
      <![CDATA[result/screenshot/2018_08_10_14_19_21_toOver.jpg]]>
    </line>
    <line>
      <![CDATA[<img src="../../result/screenshot/2018_08_10_14_19_21_toOver.jpg"/>]]>
    </line>
    <line>
      <![CDATA[result/screenshot/2018_08_10_14_19_46_toOver.jpg]]>
    </line>
    <line>
      <![CDATA[<img src="../../result/screenshot/2018_08_10_14_19_46_toOver.jpg"/>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="113661" started-at="2018-08-10T06:17:54Z" finished-at="2018-08-10T06:19:48Z">
    <groups>
      <group name="生成报溢单">
        <method signature="LoginPage_001_LoginSuccessFunction_Test.toOver()[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="toOver" class="com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test"/>
      </group> <!-- 生成报溢单 -->
      <group name="觅云测试">
        <method signature="LoginPage_001_LoginSuccessFunction_Test.toLose()[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="toLose" class="com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test"/>
        <method signature="LoginPage_001_LoginSuccessFunction_Test.toOver()[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="toOver" class="com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test"/>
      </group> <!-- 觅云测试 -->
      <group name="生成报损单">
        <method signature="LoginPage_001_LoginSuccessFunction_Test.toLose()[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="toLose" class="com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test"/>
      </group> <!-- 生成报损单 -->
    </groups>
    <test name="Login" duration-ms="113661" started-at="2018-08-10T06:17:54Z" finished-at="2018-08-10T06:19:48Z">
      <class name="com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test">
        <test-method status="PASS" signature="startTest(org.testng.ITestContext)[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="startTest" is-config="true" duration-ms="17181" started-at="2018-08-10T06:17:54Z" finished-at="2018-08-10T06:18:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@4bf3798b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="SKIP" signature="toLose()[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="toLose" duration-ms="28155" started-at="2018-08-10T06:18:11Z" finished-at="2018-08-10T06:18:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[数据对比失败，第一条数据为:-4.00,第二条数据为：-4.00，应为：-5.00，设定差值为：1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 数据对比失败，第一条数据为:-4.00,第二条数据为：-4.00，应为：-5.00，设定差值为：1
at org.testng.Assert.fail(Assert.java:96)
at com.hebg3.utils.pagehelper.PageHelperUtil.compareData(PageHelperUtil.java:90)
at com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test.toLose(LoginPage_001_LoginSuccessFunction_Test.java:127)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=2]]>
            </line>
            <line>
              <![CDATA[result/screenshot/2018_08_10_14_18_39_toLose.jpg]]>
            </line>
            <line>
              <![CDATA[<img src="../../result/screenshot/2018_08_10_14_18_39_toLose.jpg"/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- toLose -->
        <test-method status="SKIP" signature="toOver()[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="toOver" duration-ms="25672" started-at="2018-08-10T06:18:55Z" finished-at="2018-08-10T06:19:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[数据对比失败，第一条数据为:-4.00,第二条数据为：-3.00，应为：-5.00，设定差值为：1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 数据对比失败，第一条数据为:-4.00,第二条数据为：-3.00，应为：-5.00，设定差值为：1
at org.testng.Assert.fail(Assert.java:96)
at com.hebg3.utils.pagehelper.PageHelperUtil.compareData(PageHelperUtil.java:90)
at com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test.toOver(LoginPage_001_LoginSuccessFunction_Test.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[RunCount=2]]>
            </line>
            <line>
              <![CDATA[result/screenshot/2018_08_10_14_19_21_toOver.jpg]]>
            </line>
            <line>
              <![CDATA[<img src="../../result/screenshot/2018_08_10_14_19_21_toOver.jpg"/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- toOver -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test@3e27ba32]" name="endTest" is-config="true" duration-ms="1399" started-at="2018-08-10T06:19:46Z" finished-at="2018-08-10T06:19:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.hebg3.testcases.login.LoginPage_001_LoginSuccessFunction_Test -->
    </test> <!-- Login -->
  </suite> <!-- Suite -->
</testng-results>
